/* Native links also work in the static Vercel build. */
/* oxlint-disable next/no-html-link-for-pages */
import { ArrowRight, BookOpen, Cpu, ExternalLink, ShieldCheck, Terminal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { handbookUrl } from '@/lib/pages';

const topics = [
  { id: 'quickstart', title: 'Start with the marketplace', description: 'Explore models, compare providers, and try the demo checkout.', icon: BookOpen },
  { id: 'providers', title: 'Bring your own compute', description: 'Understand the provider pilot and what a worker needs to serve.', icon: Cpu },
  { id: 'pilot', title: 'Connect a real model', description: 'A private, authenticated API for the first controlled inference test.', icon: Terminal },
  { id: 'status', title: 'Know what is live', description: 'A clear boundary between the product demo and the planned network.', icon: ShieldCheck },
];

export function Documentation() {
  return (
    <section className="mx-auto max-w-[1480px] px-5 py-20 lg:px-10 lg:py-28">
      <div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end">
        <div><p className="mb-3 text-[10px] uppercase tracking-[.18em] text-[#c8ff30]">The Roox handbook</p><h1 className="text-4xl font-medium leading-[.95] tracking-[-.055em] sm:text-6xl">Understand the network.<br /><span className="text-white/40">Build with confidence.</span></h1></div>
        <Button render={<a href={handbookUrl} aria-label="Full documentation" target="_blank" rel="noopener noreferrer" />} className="h-11 self-start rounded-full bg-white px-5 text-sm text-black">Full documentation <ExternalLink data-icon="inline-end" /></Button>
      </div>
      <nav aria-label="Documentation topics" className="mt-10 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        {topics.map(({ id, title, description, icon: Icon }) => <a key={id} href={'#' + id} className="group rounded-[22px] border border-white/10 bg-[#0e100f] p-5 transition-colors hover:border-white/25"><Icon className="size-5 text-[#c8ff30]" /><h2 className="mt-6 text-lg font-medium tracking-[-.035em]">{title}</h2><p className="mt-2 text-xs leading-5 text-white/45">{description}</p><ArrowRight className="mt-5 size-4 text-white/45 transition-transform group-hover:translate-x-1" /></a>)}
      </nav>
      <div className="mt-10 rounded-[22px] border border-[#c8ff30]/20 bg-[#c8ff30]/[.04] p-6 text-sm leading-6 text-white/65"><span className="font-medium text-[#c8ff30]">Preview, not a paid network.</span> Marketplace cards and statistics are demo data. The checkout is simulated. The private inference pilot is disabled until a real worker is configured; it does not sign receipts or settle payments.</div>
      <div className="mt-16 grid gap-16 lg:grid-cols-[1fr_2fr]">
        <aside className="text-sm leading-6 text-white/45"><p className="text-[10px] uppercase tracking-[.18em] text-[#c8ff30]">One product. Four pages.</p><p className="mt-4">Explore the overview, find a model in the marketplace, prepare your GPU, and return here whenever you need the details.</p><a href="https://github.com/0xNexuz/roox" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 text-white hover:text-[#c8ff30]">View source <ExternalLink className="size-3" /></a></aside>
        <div className="space-y-14">
          <article id="quickstart" className="scroll-mt-24 border-b border-white/10 pb-12"><p className="text-[10px] uppercase tracking-[.18em] text-[#c8ff30]">01 / Quickstart</p><h2 className="mt-3 text-3xl font-medium tracking-[-.045em]">Your first demo call.</h2><ol className="mt-6 list-decimal space-y-3 pl-5 text-sm leading-6 text-white/55"><li>Open the <a href="/market" className="text-white underline underline-offset-4">marketplace</a> and search by model, GPU, provider, or region.</li><li>Use the workload filters to compare the available demo cards.</li><li>Select <span className="text-white">Run a call</span> and review the estimate.</li><li>Select <span className="text-white">Run test call</span>. This shows the intended workflow without spending funds.</li></ol><p className="mt-6 text-xs leading-6 text-white/40">Connecting a wallet is not a payment authorization or an account login. No transaction-signing or settlement flow is enabled.</p></article>
          <article id="providers" className="scroll-mt-24 border-b border-white/10 pb-12"><p className="text-[10px] uppercase tracking-[.18em] text-[#c8ff30]">02 / Providers</p><h2 className="mt-3 text-3xl font-medium tracking-[-.045em]">Start with one trusted worker.</h2><p className="mt-6 text-sm leading-6 text-white/55">The first pilot connects an operator-controlled model endpoint over HTTPS. Keep its access key server-side, select one allowed model, and test bounded requests before admitting outside traffic.</p><ul className="mt-5 list-disc space-y-2 pl-5 text-sm leading-6 text-white/55"><li>A model-serving endpoint and permission to run the model.</li><li>Known hardware capacity, request limits, and a health-check process.</li><li>Private credentials and a clear policy for prompt retention.</li><li>End-to-end testing before public onboarding or payments.</li></ul><p className="mt-5 text-xs leading-6 text-white/40">An installable Roox worker, live provider registry, and payouts remain planned. The provider button leads here; it does not register your machine automatically.</p></article>
          <article id="pilot" className="scroll-mt-24 border-b border-white/10 pb-12"><p className="text-[10px] uppercase tracking-[.18em] text-[#c8ff30]">03 / Developer pilot</p><h2 className="mt-3 text-3xl font-medium tracking-[-.045em]">Real execution. Explicit limits.</h2><p className="mt-6 text-sm leading-6 text-white/55">The private pilot endpoint accepts an operator access key and forwards a bounded prompt only to the configured model server. Missing configuration returns an unavailable response, never a fabricated success.</p><pre className="mt-6 overflow-x-auto rounded-2xl border border-white/10 bg-black/30 p-5 font-mono text-xs leading-6 text-white/65"><code>{'POST /api/inference\nAuthorization: Bearer <operator-access-key>\nContent-Type: application/json\n\n{\n  "model": "<configured-model>",\n  "prompt": "Explain GPU inference in one sentence.",\n  "max_tokens": 128\n}'}</code></pre><p className="mt-5 text-xs leading-6 text-white/40">This is an operator-only pilot, not a public API product. A successful response is not a verified receipt. No customer charges or onchain settlement occur; running your worker can still have infrastructure costs.</p></article>
          <article id="status" className="scroll-mt-24"><p className="text-[10px] uppercase tracking-[.18em] text-[#c8ff30]">04 / Launch readiness</p><h2 className="mt-3 text-3xl font-medium tracking-[-.045em]">What exists. What comes next.</h2><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[320px] text-left text-sm"><caption className="sr-only">Roox implementation status</caption><thead className="bg-white/[.04] text-white/70"><tr><th scope="col" className="p-4 font-medium">Capability</th><th scope="col" className="p-4 font-medium">Status</th></tr></thead><tbody className="divide-y divide-white/10 text-white/50">{[['Pages, search, filters, demo checkout', 'Available'], ['Operator inference gateway', 'Implemented; configuration required'], ['Live GPU providers and real model test', 'Awaiting a worker'], ['Customer accounts, quotas, billing', 'Not implemented'], ['Signed receipts and settlement', 'Not implemented'], ['Public-launch security and load testing', 'Required before paid access']].map(([name, status]) => <tr key={name}><th scope="row" className="p-4 font-normal">{name}</th><td className="p-4">{status}</td></tr>)}</tbody></table></div><a href={handbookUrl} className="mt-6 inline-flex items-center gap-2 text-sm text-white hover:text-[#c8ff30]">Continue in GitBook <ArrowRight className="size-4" /></a></article>
        </div>
      </div>
    </section>
  );
}
